/* FICTIONAL DATA — every person, message and meal here is invented for the prototype.
   Shape mirrors what the real integration would need; see README "Data model". */
window.EC_DATA = {
  professional: { name: "Dra. Ana Ribeiro", role: "Nutritionist", initials: "AR" },
  today: "2026-10-05",

  recipes: [
    { id: "r1", name: "Overnight oats with pear & walnuts", meal: "breakfast", mins: 5, tags: ["vegetarian", "quick"], dairy: true, gluten: true },
    { id: "r2", name: "Lactose-free oats with berries", meal: "breakfast", mins: 5, tags: ["vegetarian", "quick", "lactose-free"], dairy: false, gluten: true },
    { id: "r3", name: "Scrambled eggs on rye", meal: "breakfast", mins: 8, tags: ["vegetarian", "quick", "protein"], dairy: false, gluten: true },
    { id: "r4", name: "Chia pudding with mango", meal: "breakfast", mins: 5, tags: ["vegan", "vegetarian", "quick", "lactose-free", "gluten-free"], dairy: false, gluten: false },
    { id: "r5", name: "Chickpea & spinach stew", meal: "dinner", mins: 20, tags: ["vegan", "vegetarian", "lactose-free", "gluten-free", "batch"], dairy: false, gluten: false },
    { id: "r6", name: "One-tray salmon & vegetables", meal: "dinner", mins: 25, tags: ["protein", "lactose-free", "gluten-free"], dairy: false, gluten: false },
    { id: "r7", name: "15-minute lentil bolognese", meal: "dinner", mins: 15, tags: ["vegan", "vegetarian", "quick", "lactose-free", "batch"], dairy: false, gluten: true },
    { id: "r8", name: "Greek yoghurt bowl", meal: "snack", mins: 3, tags: ["vegetarian", "quick", "protein"], dairy: true, gluten: false },
    { id: "r9", name: "Hummus & crunchy veg", meal: "snack", mins: 5, tags: ["vegan", "vegetarian", "quick", "lactose-free", "gluten-free"], dairy: false, gluten: false },
    { id: "r10", name: "Chicken & quinoa bowl", meal: "lunch", mins: 20, tags: ["protein", "lactose-free", "gluten-free", "batch"], dairy: false, gluten: false },
    { id: "r11", name: "Banana & peanut toast", meal: "snack", mins: 4, tags: ["vegan", "vegetarian", "quick", "pre-training"], dairy: false, gluten: true },
    { id: "r12", name: "Tofu stir-fry with rice", meal: "dinner", mins: 20, tags: ["vegan", "vegetarian", "lactose-free", "protein"], dairy: false, gluten: false },
  ],

  clients: [
    {
      id: "rui", name: "Rui Santos", initials: "RS", age: 34, since: "2026-06-02", tone: "#e3e8dc",
      status: "consult", statusNote: "Consultation today · 15:30",
      nextAppointment: { date: "2026-10-05", time: "15:30", kind: "Follow-up · video" },
      lastConsult: "2026-09-12",
      sharing: { meals: true, reflections: true, recipes: true, buddy: false },
      goals: ["More energy at work", "Regular meals on shift days"],
      clinical: "Mild iron deficiency (bloods, July). No medication. Works rotating shifts since September.",
      care: {
        version: 4, updated: "2026-09-12",
        objectives: ["More regular meals on workdays", "Steady energy through the afternoon"],
        needs: ["Iron-rich foods several times a week"],
        preferences: ["Vegetarian most days", "Quick to prepare"],
        restrictions: ["Lactose intolerance"],
        priorities: ["Regular breakfasts on workdays", "Simple weeknight dinners"],
      },
      meals: [
        { date: "2026-10-04", meal: "Breakfast", caption: "Lactose-free oats, berries", reflection: "Made it the night before, first time this week." },
        { date: "2026-10-03", meal: "Dinner", caption: "Takeaway noodles", reflection: "Got home at 22h, no energy to cook." },
        { date: "2026-10-02", meal: "Lunch", caption: "Chickpea stew from Sunday batch", reflection: "Batch cooking is helping." },
        { date: "2026-10-01", meal: "Breakfast", caption: "Toast & coffee on the way", reflection: "" },
        { date: "2026-09-29", meal: "Dinner", caption: "Lentil bolognese", reflection: "Easy, would do again." },
      ],
      reflectionsCount: 4, mealsCount: 9,
      recipes: { liked: ["r2", "r5", "r7"], saved: ["r12"], skipped: ["r1"] },
      messages: [
        { from: "client", date: "2026-10-03 21:40", text: "Late shifts again this week. Is it OK to have a bigger lunch and something light at night?", judgement: true, answered: false },
        { from: "pro", date: "2026-09-20 10:02", text: "Great to hear the batch cooking is working. Keep the Sunday routine!" },
      ],
      changes: [
        { date: "2026-09-12", text: "Care Profile v4: added ‘Simple weeknight dinners’ as a priority." },
        { date: "2026-09-08", text: "Started rotating shifts (from his reflection)." },
        { date: "2026-08-20", text: "Breakfast on workdays: from rare to most days (from shared meals)." },
      ],
      patterns: ["Breakfasts became more regular on workdays since the last consultation.", "Late-shift evenings tend to end in takeaway."],
      topics: ["Weeknight dinners that survive a late shift", "How the new shift pattern is going", "Iron: follow-up bloods?"],
    },
    {
      id: "ines", name: "Inês Martins", initials: "IM", age: 28, since: "2026-08-10", tone: "#f3d8cf",
      status: "attention", statusNote: "Question waiting for your judgement",
      nextAppointment: { date: "2026-10-14", time: "10:00", kind: "Follow-up · in person" },
      lastConsult: "2026-09-16",
      sharing: { meals: true, reflections: true, recipes: true, buddy: false },
      goals: ["Fuel training for a half-marathon", "Feel less bloated"],
      clinical: "Suspected IBS, under GP follow-up. Low-FODMAP trial discussed, not started.",
      care: {
        version: 2, updated: "2026-09-16",
        objectives: ["Fuel training sessions well", "Reduce discomfort after meals"],
        needs: ["Carbohydrate before long runs"],
        preferences: ["Likes cooking at weekends"],
        restrictions: [],
        priorities: ["A pre-training snack routine"],
      },
      meals: [
        { date: "2026-10-04", meal: "Snack", caption: "Banana & peanut toast before run", reflection: "Felt much better on the 14k." },
        { date: "2026-10-02", meal: "Dinner", caption: "Tofu stir-fry", reflection: "Bloated after, not sure why." },
      ],
      reflectionsCount: 3, mealsCount: 6,
      recipes: { liked: ["r11", "r12"], saved: ["r4"], skipped: [] },
      messages: [
        { from: "client", date: "2026-10-04 08:12", text: "Should I eat before my early 7am runs or is it fine to go fasted?", judgement: true, answered: false },
      ],
      changes: [
        { date: "2026-09-16", text: "Care Profile v2: priority ‘A pre-training snack routine’." },
        { date: "2026-09-30", text: "Mentioned bloating after dinners twice (from reflections)." },
      ],
      patterns: ["Reports feeling better on runs when she eats beforehand.", "Bloating mentioned after two dinners this fortnight; possible link worth exploring, not a conclusion."],
      topics: ["Fasted vs fed early runs", "Bloating after dinners", "Start the low-FODMAP trial?"],
    },
    {
      id: "carla", name: "Carla Lopes", initials: "CL", age: 46, since: "2026-05-18", tone: "#f4e8cf",
      status: "checkin", statusNote: "Shared less this week",
      nextAppointment: { date: "2026-10-21", time: "18:00", kind: "Follow-up · video" },
      lastConsult: "2026-09-23",
      sharing: { meals: true, reflections: true, recipes: false, buddy: false },
      goals: ["Eat more calmly", "Cook more at home"],
      clinical: "Perimenopause symptoms. Type 2 diabetes in family history.",
      care: {
        version: 5, updated: "2026-09-23",
        objectives: ["Calmer, unhurried meals", "More home-cooked dinners"],
        needs: ["Fibre at most meals"],
        preferences: ["Mediterranean flavours"],
        restrictions: ["Gluten-free"],
        priorities: ["Sitting down for lunch", "Two home-cooked dinners a week"],
      },
      meals: [{ date: "2026-09-29", meal: "Lunch", caption: "Salad at the desk", reflection: "Busy week." }],
      reflectionsCount: 1, mealsCount: 2,
      recipes: { liked: [], saved: [], skipped: [] },
      messages: [{ from: "client", date: "2026-09-28 19:05", text: "Work is crazy this month, sorry for the silence!", judgement: false, answered: false }],
      changes: [{ date: "2026-09-23", text: "Care Profile v5: priority ‘Sitting down for lunch’." }],
      patterns: ["Fewer moments shared in the last 10 days, after a busy-work message. Quiet isn’t a problem in itself; a light check-in may help."],
      topics: ["How is the busy month going?", "Smallest version of ‘sitting down for lunch’"],
    },
    {
      id: "joao", name: "João Pereira", initials: "JP", age: 52, since: "2026-04-01", tone: "#e3e8dc",
      status: "steady", statusNote: "Steady",
      nextAppointment: { date: "2026-10-28", time: "11:00", kind: "Follow-up · in person" },
      lastConsult: "2026-09-30",
      sharing: { meals: true, reflections: false, recipes: true, buddy: false },
      goals: ["Support blood pressure", "Less salt without losing flavour"],
      clinical: "Hypertension, on medication (GP). Lower-sodium plan agreed.",
      care: {
        version: 6, updated: "2026-09-30",
        objectives: ["Flavour without added salt"],
        needs: ["Lower sodium"],
        preferences: ["Fish twice a week"],
        restrictions: [],
        priorities: ["Herbs and spices instead of salt"],
      },
      meals: [{ date: "2026-10-03", meal: "Dinner", caption: "One-tray salmon & vegetables", reflection: "" }],
      reflectionsCount: 0, mealsCount: 7,
      recipes: { liked: ["r6", "r10"], saved: [], skipped: [] },
      messages: [],
      changes: [{ date: "2026-09-30", text: "Care Profile v6 reviewed, no changes." }],
      patterns: ["Fish shared twice a week for three weeks."],
      topics: ["Keep what’s working"],
    },
    {
      id: "sofia", name: "Sofia Almeida", initials: "SA", age: 31, since: "2026-10-01", tone: "#f3d8cf",
      status: "new", statusNote: "New connection · first consultation tomorrow",
      nextAppointment: { date: "2026-10-06", time: "09:30", kind: "First consultation · video" },
      lastConsult: null,
      sharing: { meals: true, reflections: true, recipes: true, buddy: false },
      goals: ["Find a way of eating that fits a busy life"],
      clinical: "To be completed at first consultation.",
      care: { version: 0, updated: null, objectives: [], needs: [], preferences: ["Vegan"], restrictions: [], priorities: [] },
      meals: [{ date: "2026-10-03", meal: "Lunch", caption: "Hummus & crunchy veg", reflection: "My go-to when I’m busy." }],
      reflectionsCount: 1, mealsCount: 3,
      recipes: { liked: ["r9", "r5"], saved: ["r4"], skipped: [] },
      messages: [{ from: "client", date: "2026-10-02 12:30", text: "Hi! Looking forward to our first session.", judgement: false, answered: true }],
      changes: [{ date: "2026-10-01", text: "Connected from the Eat Conscience app." }],
      patterns: ["Not enough shared yet to see patterns. That’s expected for a new connection."],
      topics: ["What does a ‘busy day’ look like?", "What she wants from the app between sessions"],
    },
    {
      id: "miguel", name: "Miguel Costa", initials: "MC", age: 39, since: "2026-07-07", tone: "#f4e8cf",
      status: "steady", statusNote: "Steady",
      nextAppointment: { date: "2026-11-04", time: "17:00", kind: "Follow-up · video" },
      lastConsult: "2026-09-02",
      sharing: { meals: true, reflections: true, recipes: true, buddy: true },
      goals: ["Less snacking at night"],
      clinical: "No relevant history reported.",
      care: {
        version: 3, updated: "2026-09-02",
        objectives: ["A satisfying dinner so evenings feel calmer"],
        needs: ["Protein at dinner"],
        preferences: ["Loves spicy food"],
        restrictions: [],
        priorities: ["A filling dinner before 21h"],
      },
      meals: [{ date: "2026-10-04", meal: "Dinner", caption: "Tofu stir-fry with chilli", reflection: "No late snacking tonight." }],
      reflectionsCount: 5, mealsCount: 10,
      recipes: { liked: ["r12", "r6"], saved: ["r7"], skipped: [] },
      messages: [{ from: "client", date: "2026-10-01 22:10", text: "Shared a Buddy chat with you about stressful evenings, in case it helps.", judgement: false, answered: false, sharedBuddy: true }],
      changes: [{ date: "2026-10-01", text: "Chose to share one Buddy conversation with you." }],
      patterns: ["Evenings with an earlier dinner are described as calmer in his reflections."],
      topics: ["What helps on stressful evenings (shared Buddy chat)"],
    },
  ],
};
